### ISSUE TITLE
Error installing this extension

### ISSUE THREAD

**Issue by EnriGrossi** [n3wt0n/WorkItemsHistory#1]
when I click install I get this error:

![errortfs](https://cloud.githubusercontent.com/assets/12607857/20661384/caa28cd8-b54e-11e6-994c-8cf9ef184673.jpg)

Enri

**Comment by n3wt0n** [comment]
Thanks for reporting this. Are you trying to install it on VSTS or TFS?

**Comment by EnriGrossi** [comment]
TFS 2015

Enri

**Comment by n3wt0n** [comment]
It seems there was a small problem with the extensions manifest... Could you retry now with the version 1.0.1?

**Comment by EnriGrossi** [comment]
Perfect.

Tyvm

Enri

**Comment by n3wt0n** [comment]
Fixed with commit 54a5b4194f689c21fb34b60c5066143f9a9b20b1
