### ISSUE TITLE
Not showing color for UserStory and Custom WI.

### ISSUE THREAD

**Issue by dvryltsov** [n3wt0n/WorkItemsHistory#2]
Hello!

In the history are displayed incorrectly colored elements.
Team Foundation Server 2015 Update 3

We used two WITTT type with the following parameters:
```
<WorkItemColor primary = "FF009CCC" secondary = "FFD6ECF2" name = "User Story" />
<WorkItemColor primary = "FF29C446" secondary = "FF29C446" name = "Technical Story" />
```

![image](https://cloud.githubusercontent.com/assets/226718/21091115/5b39df06-c055-11e6-9a3b-6a36ae00b15d.png)

**Comment by n3wt0n** [comment]
Thanks for reporting it.

At the moment, the extension doesn't support the custom WITs.

I will update it soon to support it.

**Comment by n3wt0n** [comment]
I've implemented this feature for VSTS users.

Unfortunately, there is no API yet in TFS to retrieve the custom WITs color. It may be available in the TFS 2017 Update 1. 

At the moment the extension will show a neutral gray color for custom WITs.

**Comment by n3wt0n** [comment]
This extension is not anymore supported, it's features have been superseeded by Azure DevOps directly.

Closing all the issues.
